Repository joomla-projects/media-manager-improvement, pull requests merged in 2018-04, with the labels that each got.

#534 [ Fix ] Actions on directories does not close itself
  administrator/components/com_media/resources/scripts/components/browser/items/directory.vue
  administrator/components/com_media/resources/scripts/components/browser/items/file.vue
  administrator/components/com_media/resources/scripts/components/browser/items/video.vue
  media/com_media/js/mediamanager.js
  media/com_media/js/mediamanager.js.map
Labels: UX/UI, bug

#531 Feature - Copy url of a file to clipboard
  administrator/components/com_media/resources/scripts/components/app.vue
  administrator/components/com_media/resources/scripts/components/browser/items/file.vue
  administrator/components/com_media/resources/scripts/components/browser/items/image.vue
  administrator/components/com_media/resources/scripts/components/browser/items/video.vue
  administrator/components/com_media/resources/scripts/components/modals/share-modal.vue
  administrator/components/com_media/resources/scripts/mediamanager.js
  administrator/components/com_media/resources/scripts/store/actions.js
  administrator/components/com_media/resources/scripts/store/mutation-types.js
  administrator/components/com_media/resources/scripts/store/mutations.js
  administrator/components/com_media/resources/scripts/store/state.js
  administrator/components/com_media/tmpl/media/default_texts.php
  administrator/language/en-GB/en-GB.com_media.ini
  language/en-GB/en-GB.com_media.ini
  media/com_media/js/mediamanager.js
  media/com_media/js/mediamanager.js.map
Labels: feature

#536 Select all check box correction
  administrator/components/com_media/resources/scripts/components/toolbar/toolbar.vue
  media/com_media/js/mediamanager.js
  media/com_media/js/mediamanager.js.map
Labels: UX/UI
