Repository joomla-projects/media-manager-improvement, pull requests merged in 2018-05, with the labels that each got.

#542 Fix file get renamed to an existing file
  administrator/components/com_media/Controller/ApiController.php
Labels: bug

#546 Use the standard button as apply doesn't exist anymore
  libraries/src/Toolbar/ToolbarHelper.php
Labels: bug

#541 Fix scroll in browser
  administrator/components/com_media/resources/scripts/components/browser/browser.vue
  administrator/components/com_media/resources/styles/components/_layout.scss
  administrator/components/com_media/resources/styles/components/_media-browser.scss
  media/com_media/css/mediamanager.css
  media/com_media/css/mediamanager.min.css
  media/com_media/js/mediamanager.min.js
Labels: bug

#548 Update front dispatcher
  components/com_media/dispatcher.php
Labels: bug

#551 Deselect the 90 degrees button when rotated by specific value
  media/plg_media-action_rotate/js/rotate.es6.js
  media/plg_media-action_rotate/js/rotate.es6.min.js
  media/plg_media-action_rotate/js/rotate.js
  media/plg_media-action_rotate/js/rotate.min.js
Labels: bug

#540 Confirm delete modal
  .eslintignore
  administrator/components/com_media/resources/scripts/components/app.vue
  administrator/components/com_media/resources/scripts/components/browser/items/directory.vue
  administrator/components/com_media/resources/scripts/components/browser/items/file.vue
  administrator/components/com_media/resources/scripts/components/browser/items/image.vue
  administrator/components/com_media/resources/scripts/components/browser/items/video.vue
  administrator/components/com_media/resources/scripts/components/modals/confirm-delete-modal.vue
  administrator/components/com_media/resources/scripts/mediamanager.js
  administrator/components/com_media/resources/scripts/store/mutation-types.js
  administrator/components/com_media/resources/scripts/store/mutations.js
  administrator/components/com_media/resources/scripts/store/state.js
  administrator/components/com_media/tmpl/media/default_texts.php
  administrator/language/en-GB/en-GB.com_media.ini
  media/com_media/js/mediamanager.min.js
Labels: enhancement

#552 Add save events for content plugins
  administrator/components/com_media/Model/ApiModel.php
  administrator/language/en-GB/en-GB.plg_media-action_resize.ini
  plugins/media-action/resize/resize.php
  plugins/media-action/resize/resize.xml
Labels: feature
